services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=desafio_db;Username=postgres;Password=postgres
      Jwt__Key: "chave-super-secreta-muito-grande"
      Jwt__Issuer: "MinhaApi"
      Jwt__Audience: "MinhaApi"
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  dbdata:
